version: "3.8"

services:
  # Spring Boot приложение
  app:
    build: .
    container_name: task-management-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/TaskManagment
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Chelovek051403
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
      - JWT_LIFETIME=PT1H
    depends_on:
      - db
    networks:
      - task-net

  # PostgreSQL база данных
  db:
    image: postgres:latest
    container_name: task-management-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chelovek051403
      POSTGRES_DB: TaskManagment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - task-net

  # Swagger UI (опционально)
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_UI_URL=http://task-management-app:8080/v3/api-docs

volumes:
  postgres-data:

networks:
  task-net:
    driver: bridge
